branch: main
check:
- CUSTOM_TAG_1
- CUSTOM_TAG_2
directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
output: cli
external-checks-dir: tag_checks